dist: trusty
addons:
  apt:
    packages:
    - libdbus-c++-bin
language: cpp
before_script: cd mazda
script: make clean install
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: AndroidAuto_*.zip
    file_glob: true
    overwrite: true
    skip_cleanup: true
    on:
      tags: true
